name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Pack
      run: dotnet pack -c Release -o .artifacts --no-restore --no-build
    
    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: .artifacts/*.nupkg
